CREATE SCHEMA IF NOT EXISTS arachne;

CREATE TABLE IF NOT EXISTS arachne.attacks (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  timestamp TIMESTAMP WITH TIME ZONE NULL DEFAULT NOW(),
  ip_address TEXT NOT NULL,
  username TEXT NULL,
  password TEXT NULL,
  city TEXT NULL,
  country TEXT NULL,
  latitude DOUBLE PRECISION NULL,
  longitude DOUBLE PRECISION NULL,
  notes TEXT NULL
);


# Notes - Use identify as ID, prevents bulk inserts with IDs
